package com.dayuan.mapper.ledger;

import java.util.List;

import com.dayuan.bean.ledger.BaseLedgerHistory;
import com.dayuan.mapper.BaseMapper;

public interface BaseLedgerHistoryMapper extends BaseMapper<BaseLedgerHistory, String>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_ledger_history
     *
     * @mbg.generated Wed Jun 27 11:15:02 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_ledger_history
     *
     * @mbg.generated Wed Jun 27 11:15:02 CST 2018
     */
    int insert(BaseLedgerHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_ledger_history
     *
     * @mbg.generated Wed Jun 27 11:15:02 CST 2018
     */
    int insertSelective(BaseLedgerHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_ledger_history
     *
     * @mbg.generated Wed Jun 27 11:15:02 CST 2018
     */
    BaseLedgerHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_ledger_history
     *
     * @mbg.generated Wed Jun 27 11:15:02 CST 2018
     */
    int updateByPrimaryKeySelective(BaseLedgerHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_ledger_history
     *
     * @mbg.generated Wed Jun 27 11:15:02 CST 2018
     */
    int updateByPrimaryKey(BaseLedgerHistory record);
    
    
    /**
     * 根据条件查询输入历史
     * @param bean
     * @return
     */
    List<BaseLedgerHistory>		selectHistoryData(BaseLedgerHistory bean);
}