package com.dayuan.mapper.ledger;

import java.util.List;

import com.dayuan.bean.ledger.BaseLedgerObjHistory;
import com.dayuan.mapper.BaseMapper;

public interface BaseLedgerObjHistoryMapper extends BaseMapper<BaseLedgerObjHistory, String>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_ledger_obj_history
     *
     * @mbg.generated Wed Jul 04 16:35:33 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_ledger_obj_history
     *
     * @mbg.generated Wed Jul 04 16:35:33 CST 2018
     */
    int insert(BaseLedgerObjHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_ledger_obj_history
     *
     * @mbg.generated Wed Jul 04 16:35:33 CST 2018
     */
    int insertSelective(BaseLedgerObjHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_ledger_obj_history
     *
     * @mbg.generated Wed Jul 04 16:35:33 CST 2018
     */
    BaseLedgerObjHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_ledger_obj_history
     *
     * @mbg.generated Wed Jul 04 16:35:33 CST 2018
     */
    int updateByPrimaryKeySelective(BaseLedgerObjHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_ledger_obj_history
     *
     * @mbg.generated Wed Jul 04 16:35:33 CST 2018
     */
    int updateByPrimaryKey(BaseLedgerObjHistory record);
    /**
     * 获取历史数据
     * @param bean
     * @return
     */
    List<BaseLedgerObjHistory>	selectHistoryData(BaseLedgerObjHistory bean);
    /**
     * 获取市场历史数据
     * @param bean
     * @return
     */
    List<BaseLedgerObjHistory>	selectHistoryObj(BaseLedgerObjHistory bean);
    
    /**
     * 获取档口历史数据
     * @param bean
     * @return
     */
    List<BaseLedgerObjHistory>	selectHistoryBus(BaseLedgerObjHistory bean);
    
}