package com.dayuan.mapper.wxAccount;

import java.util.List;

import com.dayuan.bean.Page;
import com.dayuan.bean.wxAccount.wxAccount;
import com.dayuan.mapper.BaseMapper;
import com.dayuan.model.wxAccount.wxAccountModel;

public interface wxAccountMapper extends BaseMapper<wxAccount, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated Wed Nov 07 09:40:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated Wed Nov 07 09:40:30 CST 2018
     */
    int insert(wxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated Wed Nov 07 09:40:30 CST 2018
     */
    int insertSelective(wxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated Wed Nov 07 09:40:30 CST 2018
     */
    wxAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated Wed Nov 07 09:40:30 CST 2018
     */
    int updateByPrimaryKeySelective(wxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbg.generated Wed Nov 07 09:40:30 CST 2018
     */
    int updateByPrimaryKey(wxAccount record);
    
    /**
     * 查询公众号送检人数
     * @param model
     * @return
     */
    List<wxAccountModel> selectSamUserNumByDepartCode(wxAccountModel model);
    /**
     *  查询公众号送检数量 
     * @param model
     * @return
     */
    List<wxAccountModel> selectRecordingNumByDepartCode(wxAccountModel model);
    /**
     * 查询公众号检测批次
     * @param model
     * @return
     */
    List<wxAccountModel> selectSamNumByDepartCode(wxAccountModel model);
    
    int getRowTotal2(Page page);
    
	/**
	 * 查询分页数据列表
	 * @param page
	 * @return
	 */
	List<wxAccountModel> loadDatagrid2(Page page);
}