package com.dayuan3.common.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dayuan3.common.bean.OrderObjhistory;

public interface OrderObjhistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_obj_history
     *
     * @mbg.generated Thu Jul 18 14:21:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_obj_history
     *
     * @mbg.generated Thu Jul 18 14:21:11 CST 2019
     */
    int insert(OrderObjhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_obj_history
     *
     * @mbg.generated Thu Jul 18 14:21:11 CST 2019
     */
    int insertSelective(OrderObjhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_obj_history
     *
     * @mbg.generated Thu Jul 18 14:21:11 CST 2019
     */
    OrderObjhistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_obj_history
     *
     * @mbg.generated Thu Jul 18 14:21:11 CST 2019
     */
    int updateByPrimaryKeySelective(OrderObjhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_obj_history
     *
     * @mbg.generated Thu Jul 18 14:21:11 CST 2019
     */
    int updateByPrimaryKey(OrderObjhistory record);
    /**
     * 判断keyword 是否已存在
     * @param createBy
     * @param keyType
     * @param keyId
     * @return
     */
    OrderObjhistory  selectByKeyword(@Param("createBy")Integer createBy,@Param("keyType")short keyType,@Param("keyword")String keyword,@Param("regname")String regname);
   
    /**
     * 查询来源、档口历史
     * @param createBy
     * @param keyType
     * @param keyword
     * @param regname
     * @return
     */
    List<OrderObjhistory>  selectObjHistory(@Param("createBy")Integer createBy,@Param("keyType")short keyType,@Param("regname")String regname);
    
}