package com.dayuan3.common.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dayuan.bean.data.BaseFoodType;
import com.dayuan3.common.bean.Orderhistory;
import com.dayuan3.common.bean.baseFood;
import com.dayuan3.terminal.bean.RequesterUnit;

public interface OrderhistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Thu Jul 18 14:16:23 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Thu Jul 18 14:16:23 CST 2019
     */
    int insert(Orderhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Thu Jul 18 14:16:23 CST 2019
     */
    int insertSelective(Orderhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Thu Jul 18 14:16:23 CST 2019
     */
    Orderhistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Thu Jul 18 14:16:23 CST 2019
     */
    int updateByPrimaryKeySelective(Orderhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Thu Jul 18 14:16:23 CST 2019
     */
    int updateByPrimaryKey(Orderhistory record);
    
    
    /**
     * 判断keyId 是否存在
     * @param userId
     * @param keyType
     * @param keyId
     * @return
     */
   Orderhistory  selectByKeyId(@Param("createBy")Integer createBy,@Param("keyType")short keyType,@Param("keyId")Integer keyId);
    
   /**
    * 获取样品历史表
    * @param createBy
    * @return
    */
   List<baseFood>	selectFoodHistory(Integer createBy);
   
   /**
    * 获取委托单位历史表
    * @param createBy
    * @return
    */
   	List<RequesterUnit>	selectUnitHistory(Integer createBy);


    /**
     * 根据openid和类型查询搜索的历史记录
     * @param openid
     * @param type 关键字类型，0:委托单位、1:样品、2:搜索历史
     * @author shit
     * @return
     */
    Orderhistory selectHisrotyByOpenid(@Param("openid") String openid, @Param("type") Short type);

    void updateHistory(Orderhistory orderhistory);

    void insertHistory(Orderhistory orderhistory);

}