package com.dayuan.mapper.wx;

import com.dayuan.bean.wx.WxAccesstoken;
import com.dayuan.mapper.BaseMapper;

public interface WxAccesstokenMapper extends BaseMapper<WxAccesstoken, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_accesstoken
     *
     * @mbg.generated Wed Sep 12 11:24:55 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_accesstoken
     *
     * @mbg.generated Wed Sep 12 11:24:55 CST 2018
     */
    int insert(WxAccesstoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_accesstoken
     *
     * @mbg.generated Wed Sep 12 11:24:55 CST 2018
     */
    int insertSelective(WxAccesstoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_accesstoken
     *
     * @mbg.generated Wed Sep 12 11:24:55 CST 2018
     */
    WxAccesstoken selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_accesstoken
     *
     * @mbg.generated Wed Sep 12 11:24:55 CST 2018
     */
    int updateByPrimaryKeySelective(WxAccesstoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_accesstoken
     *
     * @mbg.generated Wed Sep 12 11:24:55 CST 2018
     */
    int updateByPrimaryKey(WxAccesstoken record);
}