package com.dayuan.mapper.wx;

import com.dayuan.bean.wx.WxsignIn;
import com.dayuan.mapper.BaseMapper;
import com.dayuan.model.wx.WxsignInModel;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface WxsignInMapper extends BaseMapper<WxsignIn, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wxsign_in
     *
     * @mbg.generated Sat Jul 14 17:56:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wxsign_in
     *
     * @mbg.generated Sat Jul 14 17:56:58 CST 2018
     */
    int insert(WxsignIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wxsign_in
     *
     * @mbg.generated Sat Jul 14 17:56:58 CST 2018
     */
    int insertSelective(WxsignIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wxsign_in
     *
     * @mbg.generated Sat Jul 14 17:56:58 CST 2018
     */
    WxsignIn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wxsign_in
     *
     * @mbg.generated Sat Jul 14 17:56:58 CST 2018
     */
    int updateByPrimaryKeySelective(WxsignIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wxsign_in
     *
     * @mbg.generated Sat Jul 14 17:56:58 CST 2018
     */
    int updateByPrimaryKey(WxsignIn record);

    List<WxsignInModel> queryByDepartIds(@Param("departId") Integer departId, @Param("signDate") String signDate, @Param("nickName") String nickName);

    List<WxsignInModel> queryByUserId(@Param("userId") String userId, @Param("dateStr") String dateStr);

    /**
     * 获取签到日期
     *
     * @param departArr
     * @return
     */
    List<String> querySignDate(@Param("departArr") String[] departArr);


    /**
     * shit添加:查询签到信息
     *
     * @param map
     * @return
     */
    List<WxsignIn> selectSignIn(Map<String, Object> map);

    /**
     * 查询打卡前的考勤信息
     * @param dateStr           当前天 2018-10-18
     * @param userId            当前用户id 110
     * @param punchTime         当天上午打卡时间 2018-10-18 08:40
     */
    WxsignIn selectBeforeCardSignIn(@Param("dateStr") String dateStr, @Param("userId") Integer userId, @Param("punchTime") String punchTime);
}