package com.dayuan3.terminal.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dayuan.mapper.BaseMapper;
import com.dayuan3.terminal.bean.TopupActivities;

public interface TopupActivitiesMapper extends BaseMapper<TopupActivities, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities
     *
     * @mbg.generated Mon Oct 28 10:51:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities
     *
     * @mbg.generated Mon Oct 28 10:51:47 CST 2019
     */
    int insert(TopupActivities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities
     *
     * @mbg.generated Mon Oct 28 10:51:47 CST 2019
     */
    int insertSelective(TopupActivities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities
     *
     * @mbg.generated Mon Oct 28 10:51:47 CST 2019
     */
    TopupActivities selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities
     *
     * @mbg.generated Mon Oct 28 10:51:47 CST 2019
     */
    int updateByPrimaryKeySelective(TopupActivities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities
     *
     * @mbg.generated Mon Oct 28 10:51:47 CST 2019
     */
    int updateByPrimaryKey(TopupActivities record);
    
    
    List<TopupActivities> selectByTime(@Param("timeStart")String timeStart,@Param("timeEnd")String timeEnd);
    /**
	 * 开启启动查询 需要加入定时计划的活动
	 * @return
	 */
    List<TopupActivities> selectOfferList();
}