package com.dayuan3.terminal.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dayuan.mapper.BaseMapper;
import com.dayuan3.terminal.bean.TopupActivitiesDetail;

public interface TopupActivitiesDetailMapper extends BaseMapper<TopupActivitiesDetail, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities_detail
     *
     * @mbg.generated Mon Oct 28 10:55:33 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities_detail
     *
     * @mbg.generated Mon Oct 28 10:55:33 CST 2019
     */
    int insert(TopupActivitiesDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities_detail
     *
     * @mbg.generated Mon Oct 28 10:55:33 CST 2019
     */
    int insertSelective(TopupActivitiesDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities_detail
     *
     * @mbg.generated Mon Oct 28 10:55:33 CST 2019
     */
    TopupActivitiesDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities_detail
     *
     * @mbg.generated Mon Oct 28 10:55:33 CST 2019
     */
    int updateByPrimaryKeySelective(TopupActivitiesDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities_detail
     *
     * @mbg.generated Mon Oct 28 10:55:33 CST 2019
     */
    int updateByPrimaryKey(TopupActivitiesDetail record);
    
    List<TopupActivitiesDetail>				selectByActId(Integer id);
    
    /**
     * 批量插入数据
     * @param list
     */
    void    insertList(@Param("list")List<TopupActivitiesDetail> list);
    
    void  deleteAllByActId(@Param("userId")String userId,@Param("actId")Integer actId);
}