package com.dayuan3.terminal.mapper;

import com.dayuan.mapper.BaseMapper;
import com.dayuan3.terminal.bean.TopupActivitiesLog;

public interface TopupActivitiesLogMapper  extends BaseMapper<TopupActivitiesLog, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities_log
     *
     * @mbg.generated Mon Oct 28 10:55:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities_log
     *
     * @mbg.generated Mon Oct 28 10:55:51 CST 2019
     */
    int insert(TopupActivitiesLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities_log
     *
     * @mbg.generated Mon Oct 28 10:55:51 CST 2019
     */
    int insertSelective(TopupActivitiesLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities_log
     *
     * @mbg.generated Mon Oct 28 10:55:51 CST 2019
     */
    TopupActivitiesLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities_log
     *
     * @mbg.generated Mon Oct 28 10:55:51 CST 2019
     */
    int updateByPrimaryKeySelective(TopupActivitiesLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup_activities_log
     *
     * @mbg.generated Mon Oct 28 10:55:51 CST 2019
     */
    int updateByPrimaryKey(TopupActivitiesLog record);
}