package com.dayuan.mapper.system;

import java.util.List;

import com.dayuan.bean.system.TSDepartMap;
import com.dayuan.mapper.BaseMapper;
import com.dayuan.model.system.TSDepartMapModel;

public interface TSDepartMapMapper  extends BaseMapper<TSDepartMap, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_s_depart_map
     *
     * @mbg.generated Thu Sep 20 10:14:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_s_depart_map
     *
     * @mbg.generated Thu Sep 20 10:14:13 CST 2018
     */
    int insert(TSDepartMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_s_depart_map
     *
     * @mbg.generated Thu Sep 20 10:14:13 CST 2018
     */
    int insertSelective(TSDepartMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_s_depart_map
     *
     * @mbg.generated Thu Sep 20 10:14:13 CST 2018
     */
    TSDepartMap selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_s_depart_map
     *
     * @mbg.generated Thu Sep 20 10:14:13 CST 2018
     */
    int updateByPrimaryKeySelective(TSDepartMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_s_depart_map
     *
     * @mbg.generated Thu Sep 20 10:14:13 CST 2018
     */
    int updateByPrimaryKey(TSDepartMap record);
    
    /**
     * 根据departId查询
     * @param departId
     * @return
     */
    TSDepartMap selectByDepartid(Integer departId);
    /**
     * 根据机构id修改
     * @param record
     */
   void     updateByDepartId(TSDepartMap record);
   
   /**
    * 根据机构id查询下级各个机构数量
    * @param departId
    * @return
    */
   TSDepartMapModel selectReportByDepartid(Integer departId);
   
   /**
    * 查询机构列表定位信息
    */
   	List<TSDepartMap>	selectDepartByDepartid(TSDepartMapModel model);
}